apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-hotel-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-hotel-service
  template:
    metadata:
      labels:
        app: demo-hotel-service
    spec:
      containers:
      - name: hotel-service
        image: demo-hotel-service:latest
        imagePullPolicy: Never # Важливо для Windows, щоб брався локальний образ Minikube
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-db:3306/java_hotel_booking_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        - name: DATA_BASE_PASSWORD
          value: "root_password"
        - name: JWT_SECRET_KEY
          value: "your_secret_key"
        ports:
        - containerPort: 8087
        readinessProbe:
          httpGet:
            path: /actuator/health # Якщо актуатора немає, замініть на ваш публічний API endpoint
            port: 8087
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: demo-hotel-service
spec:
  selector:
    app: demo-hotel-service
  ports:
    - port: 8087
      targetPort: 8087