apiVersion: apps/v1
kind: Deployment
metadata:
  name: edemium-db-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edemium-db-postgresql
  template:
    metadata:
      labels:
        app: edemium-db-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: edemium-credentials
                key: db-password
          - name: POSTGRES_DB
            value: "persistent_login_db"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: edemium-db-postgresql
spec:
  selector:
    app: edemium-db-postgresql
  ports:
    - port: 5432
      targetPort: 5432