apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edemium-hotel.fullname" . }}
  labels:
    {{- include "edemium-hotel.labels" . | nindent 4 }}
spec:
  # Жодних перевірок на autoscaling, просто беремо цифру
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "edemium-hotel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "edemium-hotel.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          # Наші змінні оточення
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://{{ .Values.db.host }}:{{ .Values.db.port }}/java_hotel_booking_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
            - name: DATA_BASE_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: JWT_SECRET_KEY
              value: {{ .Values.jwt.secretKey | quote }}
              
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
              
          # Наші проби готовності (підтягуються з values.yaml)
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}