# Кількість подів для розгортання
replicaCount: 2

# Налаштування Docker образу (pullPolicy: Never важливо для локального Minikube)
image:
  repository: demo-hotel-service
  tag: "latest"
  pullPolicy: Never

# Налаштування внутрішнього сервісу Kubernetes
service:
  type: ClusterIP
  port: 8087

# Налаштування підключення до бази даних
db:
  host: edemium-db-mysql
  port: 3306
  # Пароль залишаємо порожнім! Будемо передавати безпечно через --set
  password: ""

# Налаштування безпеки
jwt:
  # Ключ залишаємо порожнім! Будемо передавати безпечно через --set
  secretKey: ""

# Налаштування перевірки "живучості" (чи не завис застосунок)
livenessProbe:
  tcpSocket:
    port: 8087
  initialDelaySeconds: 45
  periodSeconds: 20

# Налаштування перевірки готовності (коли пускати трафік)
readinessProbe:
  tcpSocket:
    port: 8087
  initialDelaySeconds: 30
  periodSeconds: 10