apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edemium-gateway.fullname" . }}
  labels:
    {{- include "edemium-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "edemium-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "edemium-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/postgres?sslmode=disable"
            - name: SPRING_DATA_REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: USER_SERVICE_URL
              value: "http://demo-user-service:8086"
            - name: BOOKING_SERVICE_URL
              value: "http://demo-hotel-service:8087"
              
            # Секрети з edemium-credentials
            - name: DATA_BASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edemium-credentials
                  key: db-password
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: edemium-credentials
                  key: jwt-secret-key
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edemium-credentials
                  key: redis-password
            - name: REMEMBER_ME_KEY
              valueFrom:
                secretKeyRef:
                  name: edemium-credentials
                  key: remember-me-key
                  
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
              
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}