replicaCount: 2

image:
  repository: api-gateway
  tag: "latest"
  pullPolicy: Never

service:
  type: NodePort
  port: 8085
  nodePort: 30085

db:
  host: edemium-db-postgresql
  port: 5432

redis:
  host: redis-cache

livenessProbe:
  tcpSocket:
    port: 8085
  initialDelaySeconds: 120
  periodSeconds: 20

readinessProbe:
  tcpSocket:
    port: 8085
  initialDelaySeconds: 120
  periodSeconds: 10

postgresql:
  fullnameOverride: "edemium-db-postgresql"
  auth:
    username: postgres
    password: admin
    database: edemium
  primary:
    persistence:
      enabled: false