name: CI Pipeline

on:
  pull_request:
    branches: [ "main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Копіюємо код репозиторію на віртуальну машину
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #завантажує всю історію комітів

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B compile --file pom.xml

      - name: Run Tests
        run: mvn -B clean test
      
      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Berkeshchuk_Hotel-Booking-System -Dsonar.organization=berkeshchuk -Dsonar.host.url=https://sonarcloud.io
